# Generated by Django 2.1 on 2018-08-27 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushpinstatconn',
            options={'ordering': ['time_stamp', 'conn_id']},
        ),
        migrations.AlterModelOptions(
            name='pushpinstatreport',
            options={'ordering': ['time_stamp']},
        ),
        migrations.AlterModelOptions(
            name='pushpinstatsub',
            options={'ordering': ['time_stamp']},
        ),
        migrations.AddField(
            model_name='pushpinstatconn',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushpinstatreport',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushpinstatsub',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
