# Generated by Django 2.1 on 2018-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testWhile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushpinStat_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_num', models.IntegerField()),
                ('rec_msg_cnt', models.IntegerField()),
                ('sent_msg_cnt', models.IntegerField()),
                ('http_resp_sent_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PushpinStat_Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=100)),
                ('sub_cnt', models.IntegerField()),
                ('unavailable', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='pushpinstat_conn',
            old_name='available',
            new_name='unavailable',
        ),
    ]
